### ISSUE TITLE
Generated spec should include `rails_helper` instead of `spec_helper`?

### ISSUE THREAD

**Issue by andrewdsmith** [sunny/actor-rails#2]
Hi! I've just started using this gem -- it looks great, thanks! -- but got stuck when using the generator. The generated spec includes `spec_helper` but probably needs to include `rails_helper` instead to ensure the actor can be auto-loaded, if you assume that the rspec-rails gem is in use and was set up with `rails generate rspec:install` as instructed. Prior to this I was getting a `uninitialized constant` error. If you agree I'll open a PR.

**Comment by sunny** [comment]
Oh, absolutely, that would be a much better default! Please do open a PR 🙏🏻
